# Generated by Django 5.1.3 on 2025-05-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_categorymodel_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'BranchModel',
                'verbose_name_plural': 'BranchModels',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='BotuserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tg id')),
                ('lang', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=100, verbose_name='Til')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Telefon raqam')),
                ('passpord_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport Id')),
                ('passport_jsh', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport Jshshr')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('passport_front', models.ImageField(blank=True, null=True, upload_to='passport/front', verbose_name='Old Rasm')),
                ('passport_back', models.ImageField(blank=True, null=True, upload_to='passport/back', verbose_name='Orqa tarafi')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.branchmodel', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'BotuserModel',
                'verbose_name_plural': 'BotuserModels',
                'db_table': 'botuser',
            },
        ),
    ]
