# Generated by Django 5.1.3 on 2025-05-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branchmodel_name_ru_branchmodel_name_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botusermodel',
            old_name='passpord_id',
            new_name='passport_id',
        ),
    ]
