# Generated by Django 5.1.3 on 2025-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_passpord_id_botusermodel_passport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusermodel',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Tg id'),
        ),
    ]
