# Generated by Django 5.1.3 on 2025-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_botusermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusermodel',
            name='passport_back',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Orqa rasm'),
        ),
        migrations.AlterField(
            model_name='botusermodel',
            name='passport_front',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Old Rasm'),
        ),
    ]
