# Generated by Django 5.1.3 on 2025-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_botusermodel_passport_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusermodel',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Tug'ilgan sana"),
        ),
    ]
