# Generated by Django 5.1.3 on 2025-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_botusermodel_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='excel/file', verbose_name='Fayl')),
                ('is_acivate', models.BooleanField(default=True, verbose_name='Faolmi ?')),
            ],
            options={
                'verbose_name': 'ExcelfileModel',
                'verbose_name_plural': 'ExcelfileModels',
                'db_table': 'ExcelFile',
            },
        ),
    ]
