# Generated by Django 5.1.3 on 2025-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_excelfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi ?'),
        ),
    ]
