# Generated by Django 5.1.3 on 2025-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_categorymodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusermodel',
            name='cargo_code',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Yuk kodi'),
        ),
    ]
