# Generated by Django 5.1.3 on 2025-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_botusermodel_cargo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargolocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_type', models.CharField(blank=True, choices=[('avia', 'Avia'), ('avto', 'Avto')], default='avia', max_length=255, null=True, verbose_name='Turi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='Googla maps')),
            ],
            options={
                'verbose_name': 'CargolocationModel',
                'verbose_name_plural': 'CargolocationModels',
                'db_table': 'CargoLocation',
            },
        ),
    ]
