# Generated by Django 5.1.3 on 2025-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cargolocationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargolocationmodel',
            name='address',
        ),
        migrations.AddField(
            model_name='cargolocationmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='faolmi ?'),
        ),
        migrations.AddField(
            model_name='cargolocationmodel',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post kod'),
        ),
    ]
