# Generated by Django 5.1.3 on 2025-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_cargolocationmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargolocationmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='faolmi ?'),
        ),
    ]
