# Generated by Django 5.1.3 on 2025-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cargolocationmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargolocationmodel',
            name='map_link',
        ),
        migrations.AddField(
            model_name='cargolocationmodel',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='cargolocationmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Telfon raqam'),
        ),
        migrations.AlterField(
            model_name='cargolocationmodel',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post id'),
        ),
    ]
