# Generated by Django 5.1.3 on 2025-05-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_cargolocationmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargolocationmodel',
            name='post_code',
        ),
    ]
